import type { Metadata } from "next";
import "@/styles/globals.css";
import LogedOffNav from "@/components/LogedOffNav";
import MainFooter from "@/components/MainFooter";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LogedOffNav />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
